"""initial_schema_20_tables

Revision ID: 19aac71a7784
Revises: 
Create Date: 2026-02-08 07:28:09.244193
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19aac71a7784'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_code', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_name_en', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('complexity', sa.String(length=20), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('structure_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_code')
    )
    op.create_table('fee_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('category_name_vi', sa.String(length=200), nullable=True),
    sa.Column('category_name_ko', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_vat_applicable', sa.Boolean(), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('validation_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_config', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('client_templates',
    sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('sheet_type', sa.String(length=20), nullable=False),
    sa.Column('sheet_name_pattern', sa.String(length=100), nullable=True),
    sa.Column('column_range', sa.String(length=20), nullable=True),
    sa.Column('total_columns', sa.Integer(), nullable=True),
    sa.Column('header_end_row', sa.Integer(), nullable=True),
    sa.Column('data_start_row', sa.Integer(), nullable=True),
    sa.Column('fee_column_start', sa.String(length=5), nullable=True),
    sa.Column('fee_column_end', sa.String(length=5), nullable=True),
    sa.Column('total_usd_column', sa.String(length=5), nullable=True),
    sa.Column('total_vnd_column', sa.String(length=5), nullable=True),
    sa.Column('vat_column', sa.String(length=5), nullable=True),
    sa.Column('grand_total_column', sa.String(length=5), nullable=True),
    sa.Column('exchange_rate_cell', sa.String(length=10), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('formula_mapping', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('fee_items',
    sa.Column('fee_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_name_vi', sa.String(length=200), nullable=True),
    sa.Column('item_name_ko', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=True),
    sa.Column('is_vat_applicable', sa.Boolean(), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculation_rule', sa.Text(), nullable=True),
    sa.Column('is_tax_inclusive', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fee_categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fee_item_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('role_permissions',
    sa.Column('role_permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_permission_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('client_exchange_rates',
    sa.Column('client_rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('currency_from', sa.String(length=10), nullable=False),
    sa.Column('currency_to', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('client_rate_id')
    )
    op.create_table('client_fee_mappings',
    sa.Column('mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('fee_item_id', sa.Integer(), nullable=False),
    sa.Column('column_letter', sa.String(length=5), nullable=False),
    sa.Column('sheet_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_vat_applicable', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_item_id'], ['fee_items.fee_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('debit_notes',
    sa.Column('debit_note_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_note_number', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=True),
    sa.Column('total_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_vnd', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('total_vat', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('grand_total_vnd', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sheet_type', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['client_templates.template_id'], ),
    sa.PrimaryKeyConstraint('debit_note_id'),
    sa.UniqueConstraint('debit_note_number')
    )
    op.create_table('exchange_rates',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_from', sa.String(length=10), nullable=False),
    sa.Column('currency_to', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('mbl', sa.String(length=100), nullable=True),
    sa.Column('hbl', sa.String(length=100), nullable=True),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.Column('no_of_pkgs', sa.Integer(), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('chargeable_weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cd_no', sa.String(length=100), nullable=True),
    sa.Column('cd_type', sa.String(length=20), nullable=True),
    sa.Column('air_ocean_rate', sa.String(length=100), nullable=True),
    sa.Column('shipment_type', sa.String(length=20), nullable=False),
    sa.Column('origin_destination', sa.String(length=200), nullable=True),
    sa.Column('back_to_back_invoice', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_app', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('system_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('validation_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('debit_note_exports',
    sa.Column('export_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_note_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('export_status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('exported_by', sa.Integer(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.debit_note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exported_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_table('debit_note_lines',
    sa.Column('line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_note_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('total_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_vnd', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('grand_total_vnd', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('freight_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('local_charges_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pay_on_behalf', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.debit_note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_table('debit_note_workflows',
    sa.Column('workflow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_note_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.debit_note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('duplicate_detections',
    sa.Column('detection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_shipment_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_type', sa.String(length=20), nullable=False),
    sa.Column('duplicate_value', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_table('shipment_fee_details',
    sa.Column('detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('fee_item_id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_vnd', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_tax_inclusive', sa.Boolean(), nullable=True),
    sa.Column('pre_tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_item_id'], ['fee_items.fee_item_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_fee_details')
    op.drop_table('duplicate_detections')
    op.drop_table('debit_note_workflows')
    op.drop_table('debit_note_lines')
    op.drop_table('debit_note_exports')
    op.drop_table('validation_logs')
    op.drop_table('system_logs')
    op.drop_table('shipments')
    op.drop_table('exchange_rates')
    op.drop_table('debit_notes')
    op.drop_table('client_fee_mappings')
    op.drop_table('client_exchange_rates')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('fee_items')
    op.drop_table('client_templates')
    op.drop_table('validation_rules')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('fee_categories')
    op.drop_table('clients')
    # ### end Alembic commands ###
