"""sprint4_selling_records

Revision ID: 31aad5754c4f
Revises: 9e0655b5d748
Create Date: 2026-02-11 10:51:40.134021
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aad5754c4f'
down_revision: Union[str, None] = '9e0655b5d748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_selling_records',
    sa.Column('selling_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False, comment='clearance/ops/co'),
    sa.Column('mssql_source_id', sa.Integer(), nullable=False, comment='MSSQL scheme PK (scheme_clearance.id_scheme_cd 등)'),
    sa.Column('mssql_cost_id', sa.Integer(), nullable=True, comment='MSSQL cost detail PK (clearance.id_clearance 등)'),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_no', sa.String(length=255), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('total_selling_vnd', sa.Numeric(precision=15, scale=2), nullable=False, comment='매출 합계 (VND)'),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False, comment='SYNCED/ERROR'),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('selling_id')
    )
    op.create_index('ix_selling_customer', 'erp_selling_records', ['customer_name'], unique=False)
    op.create_index('ix_selling_date', 'erp_selling_records', ['service_date'], unique=False)
    op.create_index('ix_selling_source', 'erp_selling_records', ['record_type', 'mssql_source_id'], unique=True)
    op.create_index('ix_selling_type', 'erp_selling_records', ['record_type'], unique=False)
    op.create_table('erp_selling_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('selling_id', sa.Integer(), nullable=False),
    sa.Column('fee_name', sa.String(length=100), nullable=False, comment='비용 항목명 (한글)'),
    sa.Column('fee_category', sa.String(length=50), nullable=True, comment='customs/transport/handling/co/other'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('mssql_source_column', sa.String(length=100), nullable=True, comment='원본 MSSQL 컬럼명 (예: phi_thong_quan)'),
    sa.ForeignKeyConstraint(['selling_id'], ['erp_selling_records.selling_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('ix_si_selling', 'erp_selling_items', ['selling_id'], unique=False)
    # 기존 테이블 인덱스는 건드리지 않음
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_si_selling', table_name='erp_selling_items')
    op.drop_table('erp_selling_items')
    op.drop_index('ix_selling_type', table_name='erp_selling_records')
    op.drop_index('ix_selling_source', table_name='erp_selling_records')
    op.drop_index('ix_selling_date', table_name='erp_selling_records')
    op.drop_index('ix_selling_customer', table_name='erp_selling_records')
    op.drop_table('erp_selling_records')
    # ### end Alembic commands ###
