"""sprint5_workflow_audit

Revision ID: 9bd2b3cd3e62
Revises: 31aad5754c4f
Create Date: 2026-02-11 11:01:31.101042
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd2b3cd3e62'
down_revision: Union[str, None] = '31aad5754c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_approval_workflows',
    sa.Column('workflow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='debit_note/purchase_order/selling_record'),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False, comment='submit/approve/reject/confirm/cancel'),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index('ix_wf_created', 'erp_approval_workflows', ['created_at'], unique=False)
    op.create_index('ix_wf_entity', 'erp_approval_workflows', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_wf_performed', 'erp_approval_workflows', ['performed_by'], unique=False)
    op.create_table('erp_audit_logs',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment='테이블명 (erp_suppliers, erp_purchase_orders 등)'),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False, comment='INSERT/UPDATE/DELETE'),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_erp_audit_action', 'erp_audit_logs', ['action'], unique=False)
    op.create_index('ix_erp_audit_at', 'erp_audit_logs', ['action_at'], unique=False)
    op.create_index('ix_erp_audit_entity', 'erp_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_erp_audit_user', 'erp_audit_logs', ['performed_by'], unique=False)
    # 기존 테이블 인덱스는 건드리지 않음
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_erp_audit_user', table_name='erp_audit_logs')
    op.drop_index('ix_erp_audit_entity', table_name='erp_audit_logs')
    op.drop_index('ix_erp_audit_at', table_name='erp_audit_logs')
    op.drop_index('ix_erp_audit_action', table_name='erp_audit_logs')
    op.drop_table('erp_audit_logs')
    op.drop_index('ix_wf_performed', table_name='erp_approval_workflows')
    op.drop_index('ix_wf_entity', table_name='erp_approval_workflows')
    op.drop_index('ix_wf_created', table_name='erp_approval_workflows')
    op.drop_table('erp_approval_workflows')
    # ### end Alembic commands ###
