"""sprint3_buying_module

Revision ID: 9e0655b5d748
Revises: b7c4d9e8f123
Create Date: 2026-02-11 10:42:29.612011
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0655b5d748'
down_revision: Union[str, None] = 'b7c4d9e8f123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_suppliers',
    sa.Column('supplier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_type', sa.String(length=50), nullable=False, comment='shipping_line/trucking/customs_broker/co_agent/other'),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='예: NET30, COD'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_erp_suppliers_supplier_code'), 'erp_suppliers', ['supplier_code'], unique=True)
    op.create_table('erp_purchase_orders',
    sa.Column('po_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False, comment='형식: PO-YYYYMM-XXXXX'),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('mssql_shipment_ref', sa.Integer(), nullable=True, comment='MSSQL debit_sharepoint.id_invoice 참조 (FK 아님)'),
    sa.Column('service_type', sa.String(length=50), nullable=True, comment='freight/handling/customs/trucking/co'),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('amount_vnd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False, comment='UNPAID/PARTIAL/PAID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='DRAFT/CONFIRMED/CANCELLED'),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['erp_suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index(op.f('ix_erp_purchase_orders_po_number'), 'erp_purchase_orders', ['po_number'], unique=True)
    op.create_index('ix_po_payment', 'erp_purchase_orders', ['payment_status'], unique=False)
    op.create_index('ix_po_status', 'erp_purchase_orders', ['status'], unique=False)
    op.create_index('ix_po_supplier', 'erp_purchase_orders', ['supplier_id'], unique=False)
    op.create_table('erp_purchase_items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('cost_category', sa.String(length=50), nullable=True, comment='freight/handling/customs/trucking/co'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_vat_applicable', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['erp_purchase_orders.po_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('ix_pi_po', 'erp_purchase_items', ['po_id'], unique=False)
    # 기존 테이블 인덱스는 건드리지 않음
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pi_po', table_name='erp_purchase_items')
    op.drop_table('erp_purchase_items')
    op.drop_index('ix_po_supplier', table_name='erp_purchase_orders')
    op.drop_index('ix_po_status', table_name='erp_purchase_orders')
    op.drop_index('ix_po_payment', table_name='erp_purchase_orders')
    op.drop_index(op.f('ix_erp_purchase_orders_po_number'), table_name='erp_purchase_orders')
    op.drop_table('erp_purchase_orders')
    op.drop_index(op.f('ix_erp_suppliers_supplier_code'), table_name='erp_suppliers')
    op.drop_table('erp_suppliers')
    # ### end Alembic commands ###
